### ISSUE TITLE
Homes wiped on client disconnect.

### ISSUE THREAD

**Issue by xDanub** [poggit-orphanage/EssentialsPE#14] opened 2018-10-11 01:14 UTC
#### Versions

* PocketMine Version: 3.2.3
* EssentialsPE Version: 4ed5c57 not sure if thats it. The ver is 2.1.0
* Game Version: PE / Windows 10: PE

#### Crashdump or console errors

``` There are no crashdumps or errors. The homes simply just get reset on client disconnect.
```/sethome <name> and then relog and /home will return as something like "You have no homes set" hoping for a quick response since this is 'essential' to my server.
<!--- Issues that do not follow this template will get closed immediatly. -->

**Comment by Ifera** [comment] 2018-10-11 02:01
Duplicate of #4

**Closed as completed by Ifera** 2018-10-11 02:01 UTC
Labels: duplicate
